# Generated by Django 5.2.8 on 2025-11-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='block_incoming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='block_outgoing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
