# Generated by Django 5.2.8 on 2025-11-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
